fixed biom equality unit tests
qiime2/q2-shogun pull request #9
Opened 2018-11-01 19:06 UTC by nbokulich

nothing was wrong with the tests, only how `biom.table.descriptive_equality` was used — it returns a strings and does not raise an error on its own. This is now fixed.

2018-11-20 13:54 UTC, thermokarst commented
@nbokulich, can you fix the failing travis runs here?

2018-11-20 13:57 UTC, nbokulich commented
cannot fix: blocked by [this](https://github.com/knights-lab/SHOGUN/pull/21)

2019-03-15 18:49 UTC, ebolyen requested changes
One change in the recipe, otherwise LGTM

2019-03-15 18:49 UTC, ebolyen commented on ci/recipe/meta.yaml
>    build:
```suggestion
   host:
```
New conda uses build for compile toolchains, it's kind of backwards compatible right now, but may as well update it.

2019-03-15 18:49 UTC, ebolyen commented on q2_shogun/tests/test_shogun.py
> +        self.assertIn('Tables appear equal', report, report)
I like this

2019-03-15 19:00 UTC, nbokulich commented
thanks @ebolyen ! I committed your change

2019-03-15 19:01 UTC, ebolyen commented on ci/recipe/meta.yaml
> +   host:
```suggestion
  host:
```

2019-03-15 19:02 UTC, ebolyen commented
@nbokulich, sorry I messed up the whitespace in the github editor :(

2019-03-15 19:14 UTC, ebolyen approved these changes

2019-03-15 19:25 UTC, merged